config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'items#index'
  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :stores do
    resources :aisles, only: [:show]
    resources :items, only: [:show] do
      resources :reviews, only: [:create, :destroy]
    end
  end


  resources :nearby_stores, only: [:index]

  # get '/item/store', to: 'items#store'

  resources :items

  resources :searches
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :aisles, dependent: :destroy
  has_many :shelves, dependent: :destroy
  has_many :searches

  has_many :storeItems, dependent: :nullify
  has_many :items, through: :storeItems

  # validates :province
  #
  # before_save :uppercase_province
  #
  # def uppercase_province
  #   province.upcase!
  # end

  geocoded_by :full_address
  after_validation :geocode

  def full_address
    "#{name} #{street_address}, #{city}, #{province.upcase} #{postal_code} Canada"
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :find_store, only: [:show]

  def index
    @stores = Store.all
  end

  # def show
  # end


  private

  def find_store
    @store = Store.find params[:id]
  end

end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/index.html.erb
<h1>Stores</h1>

<div class="container">

  <div class="row">
    <div class="col-lg-4 col-lg-offset-4">
      <input type="text" placeholder="Simple search should be her">
    </div>
  </div>

  <div class="row">
    <div class="col-lg-4 col-lg-offset-4">
      <a href="#">Link to advanced search should be here</a>
    </div>
  </div>

</div>

<div class="jumbotron">
  <% @stores.each do |store| %>
    <p><strong><%= link_to store.name, store_path(store) %></strong></p>
  <% end %>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>

app/views/stores/show.html.erb
<h3>Show Store</h3>

<p><%= @store&.name %></p>
<p>Number of Aisles in the store: <%= @store&.aisles.count %> aisles</p>
<p>Number of Rows in each Aisle: <%= @store&.aisles.first.rows.count %> rows per each aisle</p>
<p>Number of Shelves per each row: <%= @store&.aisles.first.rows.first.shelves.count %> shelves per each row</p>


<h1>Store Items</h1>
<div class="container">
  <div class="jumbotron">
    <% @store.aisles.each do |aisle| %>
    <p><%= aisle %></p>
      <% aisle.rows.each do |row| %>
      <p><%= row %></p>
        <% row.shelves.each do |shelf| %>
        <p><%= shelf %></p>
          <!-- <% shelf.items.each do |item| %> -->
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>