config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'items#index'
  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :stores do
    resources :aisles, only: [:show]
    resources :items, only: [:show] do
      resources :reviews, only: [:create, :destroy]
    end
  end


  resources :nearby_stores, only: [:index]

  # get '/item/store', to: 'items#store'

  resources :items

  resources :searches
end

app/models/aisle.rb
class Aisle < ApplicationRecord
  belongs_to :store
  has_many :rows, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, dependent: :nullify
  has_many :searches
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  # belongs_to :shelf, optional: :true
  # has_many :reviews, dependent: :destroy
  has_many :storeItems, dependent: :nullify
  has_many :stores, through: :storeItems

  has_many :shelfItems, dependent: :nullify
  has_many :shelves, through: :shelfItems
  mount_uploader :image, ImageUploader

  validates :name, uniqueness: { case_sensitive: true }

  def next
    self.class.where("id > ?", id).first
  end

  # def previuos
  #   self.class.where("id < ?", id).last
  # end

  def self.search(search)
    if search
      where(["name ILIKE ?", "%#{search}%"])
    else
      all.order(created_at: :DESC)
    end
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :store_item

  validates :rating, presence: true, inclusion: {in: 1..5}
end

app/models/row.rb
class Row < ApplicationRecord
  belongs_to :aisle
  has_many :shelves, dependent: :nullify
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :store, optional: true

  def items
    @items ||= find_items
  end
  
  private
  def find_items
    items = Item.order(:name)
    items = items.joins(:stores).where(store_id: store_id) if store_id.present?
    if store_id.present?
      store = Store.find(store_id)
      items = store.items
    end
    items = items.where("name ILIKE ?", "%#{keywords}") if keywords.present?
    items = items.where(category_id: category_id) if category_id.present?
    items = items.where("price >= ?", min_price) if min_price.present?
    items = items.where("price <= ?", max_price) if max_price.present?
    items
  end
end

app/models/shelf.rb
class Shelf < ApplicationRecord
  belongs_to :row
  belongs_to :store

  has_many :shelfItems, dependent: :nullify
  has_many :items, through: :shelfItems

end

app/models/shelf_item.rb
class ShelfItem < ApplicationRecord
  belongs_to :shelf
  belongs_to :item
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :aisles, dependent: :destroy
  has_many :shelves, dependent: :destroy
  has_many :searches

  has_many :storeItems, dependent: :nullify
  has_many :items, through: :storeItems

  # validates :province
  #
  # before_save :uppercase_province
  #
  # def uppercase_province
  #   province.upcase!
  # end

  geocoded_by :full_address
  after_validation :geocode

  def full_address
    "#{name} #{street_address}, #{city}, #{province.upcase} #{postal_code} Canada"
  end
end

app/models/store_item.rb
class StoreItem < ApplicationRecord
  belongs_to :store
  belongs_to :item

  has_many :reviews, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :reviews, dependent: :nullify

  validates :first_name, presence: true
      validates :last_name, presence: true

      VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
      validates :email, presence: true,
                        uniqueness: {case_sensitive: false},
                        format: VALID_EMAIL_REGEX
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController


  def index
    # @items = Item.all.where(["name ILIKE ?", "%#{params[:search]}%"])
    @search = Search.new
    # @newsearch = Search.new
    if params[:search_id]
      @search = Search.find(params[:search_id])
      @items = @search.items
      # @items = @search.items.paginate(:page)
    else
      @items = Item.all.search(params[:search]).limit(10)
    end

    respond_to do |format|
      format.html { render } # index.html.erb
      format.js { render } # index.js.erb
    end
  end

  def edit
    @item = Item.find params[:id]
  end

  def update
    @item = Item.find params[:id]
    item_params = params.require(:item).permit([:image])
    @item.update item_params
    redirect_to root_path
  end

  def show
    @review = Review.new

    @item = Item.find(params['id'])
    @itemsShelf = Item.find(params['id']).shelves.find_by_store_id(params['store_id'])
    @store = Store.find(params['store_id'])

    # Bellow line is to show reviews related to an item for a specific store
    @reviews = StoreItem.where(store_id: @store.id, item_id: @item.id).first.reviews.order(created_at: :DESC)

    @hash = Gmaps4rails.build_markers(@store) do |store, marker|
      marker.lat store.latitude
      marker.lng store.longitude
      marker.infowindow store.name
    end

  end


  # private
  # def item_params
  #   params.require(:item).permit(:name, :description, :sale_price, :category_id, :image,)
  # end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new
    @search = Search.new
  end

  def create
    @search = Search.create!(search_params)

    respond_to do |format|
      format.html { redirect_to items_path(search_id: @search.id) }
      format.js do
        @items = @search.items
        render
      end
    end

  end

  def update
    begin
      @search = Search.find params[:id]
    rescue
        return create
    end

    if @search.update(search_params)
      redirect_to items_path(search_id: @search.id)
    else
      redirect_to items_path
    end
  end

  def show
    @search = Search.find(params[:id])
  end

  private
  def search_params
    params.require(:search).permit(:keywords,:store_id, :category_id, :min_price, :max_price)
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :find_store, only: [:show]

  def index
    @stores = Store.all
  end

  # def show
  # end


  private

  def find_store
    @store = Store.find params[:id]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Thanks for signing up'
    else
      flash.now[:alert] = 'Please fix the errors'
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit([:first_name, :last_name, :email, :password, :password_confirmation])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/searches/_form.html.erb
<%= simple_form_for @search || Search.new, remote: true, :html => {:id => "searchForm"}  do |f| %>

      <div class="modal-header">
        <h5 class="modal-title" id="searchModalLabel">New Search</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <%= f.input :keywords, class: "form-control" %>
        <%= f.association :store, include_blank: true, prompt: 'Choose a store' %>
        <%= f.association :category, include_blank: true, prompt: 'Choose a category' %>
        <%= f.input :min_price, class: "form-control" %>
        <%= f.input :max_price, class: "form-control" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
        <%= link_to 'Reset', new_search_path, remote: true,  class: 'btn btn-primary'  %>
        <%= f.submit "Search", class:"btn btn-primary", remote: true %>
      </div>
<% end %>

app/views/searches/_new.html.erb
<!-- <button type="button" id="advanced-search" class="btn btn-info" data-toggle="modal" data-target="#searchModal" data-whatever="Search">Custom Search</button> -->
<div class="modal fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= render 'searches/form' %>
    </div>
  </div>
</div>

app/views/searches/create.js.erb
document
  .querySelector('#searchResults')
    .innerHTML = "<%= j render  'items/items', review: @review %>";
$('#searchModal').modal('hide');

app/views/searches/new.html.erb
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#searchModal" data-whatever="@mdo">Advanced Search</button>
<div class="modal fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="searchModalLabel">New Search</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for @search do |f| %>
        <form>

          <div class="form-group">
            <%= f.label :keywords, class: "form-control-label" %>
            <%= f.text_field :keywords, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :category_id, class: "form-control-label" %>
            <%= f.collection_select :category_id,
                                    Category.order(:name),
                                    :id, :name,
                                    include_blank: true,
                                    class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :min_price, class: "form-control-label" %>
            <%= f.text_field :min_price, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :max_price, class: "form-control-label" %>
            <%= f.text_field :max_price, class: "form-control" %>
          </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
        <%= f.submit "Search", class:"btn btn-primary" %>
      </div>
    </form>
      <% end %>
    </div>
  </div>
</div>

app/views/searches/new.js.erb
<% js = escape_javascript(
render('searches/form')
) %>

$('#searchModal .modal-content').html("<%= js %>");

app/views/searches/show.html.erb
<h1>Search Results</h1>

<% @search.items.each do |item| %>
  <p><strong><%= item.name %></strong></p>
  <p>Category: <%= item.category.name %></p>
  <p>Description: <%= item.description %></p>
  <p>Price: <%= item.sale_price %></p>
<% end %>