config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'items#index'
  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :stores do
    resources :aisles, only: [:show]
    resources :items, only: [:show] do
      resources :reviews, only: [:create, :destroy]
    end
  end


  resources :nearby_stores, only: [:index]

  # get '/item/store', to: 'items#store'

  resources :items

  resources :searches
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  # belongs_to :shelf, optional: :true
  # has_many :reviews, dependent: :destroy
  has_many :storeItems, dependent: :nullify
  has_many :stores, through: :storeItems

  has_many :shelfItems, dependent: :nullify
  has_many :shelves, through: :shelfItems
  mount_uploader :image, ImageUploader

  validates :name, uniqueness: { case_sensitive: true }

  def next
    self.class.where("id > ?", id).first
  end

  # def previuos
  #   self.class.where("id < ?", id).last
  # end

  def self.search(search)
    if search
      where(["name ILIKE ?", "%#{search}%"])
    else
      all.order(created_at: :DESC)
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController


  def index
    # @items = Item.all.where(["name ILIKE ?", "%#{params[:search]}%"])
    @search = Search.new
    # @newsearch = Search.new
    if params[:search_id]
      @search = Search.find(params[:search_id])
      @items = @search.items
      # @items = @search.items.paginate(:page)
    else
      @items = Item.all.search(params[:search]).limit(10)
    end

    respond_to do |format|
      format.html { render } # index.html.erb
      format.js { render } # index.js.erb
    end
  end

  def edit
    @item = Item.find params[:id]
  end

  def update
    @item = Item.find params[:id]
    item_params = params.require(:item).permit([:image])
    @item.update item_params
    redirect_to root_path
  end

  def show
    @review = Review.new

    @item = Item.find(params['id'])
    @itemsShelf = Item.find(params['id']).shelves.find_by_store_id(params['store_id'])
    @store = Store.find(params['store_id'])

    # Bellow line is to show reviews related to an item for a specific store
    @reviews = StoreItem.where(store_id: @store.id, item_id: @item.id).first.reviews.order(created_at: :DESC)

    @hash = Gmaps4rails.build_markers(@store) do |store, marker|
      marker.lat store.latitude
      marker.lng store.longitude
      marker.infowindow store.name
    end

  end


  # private
  # def item_params
  #   params.require(:item).permit(:name, :description, :sale_price, :category_id, :image,)
  # end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_items.html.erb
  <div class="container" id="searchResults">
    <% @items.each do |item| %>
    <%= render '/items/singleItem', item: item %>
    <% end %>
  </div>

app/views/items/_maps.html.erb
<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(17);
  });
</script>

app/views/items/_singleItem.html.erb
<div class="row singleItem" style="border-radius: 10px;">
  <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
    <h4 class="item-header"><%= item.name %></h4><hr />
    <h4>Category: <%= item.category.name %></h4>
    <p>
      <%= item.description %>
    </p>
    <% if item.image.present? %>
      <img src="<%= item.image.url %>" style="height: 250px; background-color: transparent;" class="img img-responsive img-circle" >
    <% else %>
    <img src="red_leaf.png" alt="" width="70%" style="height: 250px; background-color: transparent;" class="img img-responsive img-circle">
    <% end %>
    <h4>Price: $ <%= item.sale_price %></h4>
  </div>
  <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
    <h4 class="item-header">Stores</h4> <hr />
    <table class="table table-hover table-responsive">
      <thead>
        <tr>
          <th>Store Name</th>
          <th>Address</th>
        </tr>
      </thead>
      <tbody>

        <% if @search.store_id.present? %>
          <tr>
            <td class="store-link"><%= link_to @search.store.name, store_item_path(@search.store, item) %></td>
            <td><%= @search.store.full_address %></td>
          </tr>
          <% else %>

          <% item.stores.each do |store| %>
            <tr>
              <td class="store-link"><%= link_to store.name, store_item_path(store, item) %></td>
              <td><%= store.full_address %></td>
            </tr>
          <% end %>
        <% end %>

      </tbody>
    </table>
  </div>
  <hr />
</div>

app/views/items/edit.html.erb
<%= simple_form_for @item do |f| %>
  <%= f.input :image %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/items/index.html.erb
<!-- <div class="container" style="margin-top: 20px;">
  <#%= render 'layouts/navbar' %>
</div> -->
 <!-- <hr />
<div class="row">
  <div class="col-lg-12">
    <form class="simple-search-field" action="/items" accept-charset="UTF-8" method="get">
      <div class="input-group">
        <input type="text" name="search" value="" class="form-control search-field" placeholder="Search for an item...">
        <span class="input-group-btn">
          <input type="submit" name="commit" value="Search" class="btn btn-default search-button" data-disable-with="search">
        </span>
      </form>
        <span class="input-group-btn">
          <button type="button" class="btn btn-default search-button" data-toggle="modal" data-target="#searchModal" data-whatever="Search">Custom Search</button>
        </span>
    </div>
  </div>
</div> -->
<!-- <#%= render './searches/new' %> -->


<%= render 'items' %>

app/views/items/index.js.erb
document
  .querySelector('#searchResults')
    .innerHTML = "<%= j render  'items/items', review: @review %>";
document
  .getElementById('simpleSearchForm')
    .reset();

app/views/items/show.html.erb
<br>
<div class="container" style="margin-bottom: 40px;">
  <div class="row">
    <div class="col-md-7">
      <div class="row">
        <br />
        <a href="#"><%= @store.name %></a> / <a href="#"></%><%= @item.category.name %></a> / <a href="#"><%= @item.name %></a>

        <div class="picture">
          <% if @item.image.present? %>
            <img class="img-responsive" src="<%= @item.image.url %>" style="width: 80%; height: 300px;" alt="#">
          <% else %>
            <img class="img-responsive" src="http://canadianainn.ca/images/red-leaf2.png" style="width: 80%; height: 300px;" alt="#">
          <% end %>
        </div>
        <h3 style="text-align: center;">Price: <%= number_to_currency(@item.price) %></h3>
        <%= render './reviews/reviewForm' %>
          <%= render './reviews/reviewShow' %>
      </div>
    </div>
    <div class="col-md-5">
      <div class="row">
        <div class="about-content">
          <div class="row" style="border: inset #2874b4;">
            <!-- <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12" style="padding: 0px">
              <img class="img-responsive" src="http://www.tiki-international.com/projects/data1/images/superstore2.jpg" style="width: 90%; height: 200px;" alt="#">
            </div> -->
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="padding: 0px">
              <div id="map" style="width: 100%; height: 400px; border: 0px;"></div>
            </div>
          </div>
          <h3 class="content-title" style="color: #2874b4;">
            <strong>
              <%= @store.name %>
            </strong>
            <a target="_blank" jstcache="6" href="https://maps.google.com/maps?ll=<%= @store.latitude %>,<%= @store.longitude %>&amp;z=18&amp;t=m&amp;hl=en-US&amp;gl=US&amp;mapclient=apiv3&amp;cid=<%= @store.cid %>" class="btn btn-primary pull-right">Directions</a>

            <!-- <button class="btn btn-primary pull-right">Directions</button> -->
            <button class="btn btn-primary pull-right" style="margin-right: 5px;">Website</button>
          </h3> <hr />
          <h5><strong>Address: </strong><%= @store.full_address %></h5>
          <h5><strong>Phone: </strong>(700) 233-4343</h5> <hr />

          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12" style="padding: 0px">
              <h3><%= @item.name %></h3>
              <h3>Price: <%= number_to_currency(@item.price) %></h3>
              <%= link_to 'Edit', edit_item_path(@item) %>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12" style="padding: 0px">
              Find <%= @item.name %> at:
              <h5>
                <table class="table table-responsive">
                  <thead>
                    <tr>
                      <th style="text-align: center;">Aisle</th>
                      <th style="text-align: center;">Row</th>
                      <th style="text-align: center;">Shelf</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td style="border: groove #2874b4; text-align: center; background-color: whitesmoke;"><strong><%= @itemsShelf.row.aisle.aisle_number %></strong></td>
                      <td style="border: groove #2874b4; text-align: center; background-color: whitesmoke;"><strong><%= @itemsShelf.row.row_number %></strong></td>
                      <td style="border: groove #2874b4; text-align: center; background-color: whitesmoke;"><strong><%= @itemsShelf.shelf_number %></strong></td>
                    </tr>
                </table>
              </h5>
            </div>
          </div>

          <p>
            <%= @item.description %>
          </p>
        </div>
      </div>
    </div>
  </div><hr>
</div>

<%= render 'maps' %>