config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'items#index'
  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :stores do
    resources :aisles, only: [:show]
    resources :items, only: [:show] do
      resources :reviews, only: [:create, :destroy]
    end
  end


  resources :nearby_stores, only: [:index]

  # get '/item/store', to: 'items#store'

  resources :items

  resources :searches
end

app/models/aisle.rb
class Aisle < ApplicationRecord
  belongs_to :store
  has_many :rows, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, dependent: :nullify
  has_many :searches
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  # belongs_to :shelf, optional: :true
  # has_many :reviews, dependent: :destroy
  has_many :storeItems, dependent: :nullify
  has_many :stores, through: :storeItems

  has_many :shelfItems, dependent: :nullify
  has_many :shelves, through: :shelfItems
  mount_uploader :image, ImageUploader

  validates :name, uniqueness: { case_sensitive: true }

  def next
    self.class.where("id > ?", id).first
  end

  # def previuos
  #   self.class.where("id < ?", id).last
  # end

  def self.search(search)
    if search
      where(["name ILIKE ?", "%#{search}%"])
    else
      all.order(created_at: :DESC)
    end
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :store_item

  validates :rating, presence: true, inclusion: {in: 1..5}
end

app/models/row.rb
class Row < ApplicationRecord
  belongs_to :aisle
  has_many :shelves, dependent: :nullify
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :store, optional: true

  def items
    @items ||= find_items
  end
  
  private
  def find_items
    items = Item.order(:name)
    items = items.joins(:stores).where(store_id: store_id) if store_id.present?
    if store_id.present?
      store = Store.find(store_id)
      items = store.items
    end
    items = items.where("name ILIKE ?", "%#{keywords}") if keywords.present?
    items = items.where(category_id: category_id) if category_id.present?
    items = items.where("price >= ?", min_price) if min_price.present?
    items = items.where("price <= ?", max_price) if max_price.present?
    items
  end
end

app/models/shelf.rb
class Shelf < ApplicationRecord
  belongs_to :row
  belongs_to :store

  has_many :shelfItems, dependent: :nullify
  has_many :items, through: :shelfItems

end

app/models/shelf_item.rb
class ShelfItem < ApplicationRecord
  belongs_to :shelf
  belongs_to :item
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :aisles, dependent: :destroy
  has_many :shelves, dependent: :destroy
  has_many :searches

  has_many :storeItems, dependent: :nullify
  has_many :items, through: :storeItems

  # validates :province
  #
  # before_save :uppercase_province
  #
  # def uppercase_province
  #   province.upcase!
  # end

  geocoded_by :full_address
  after_validation :geocode

  def full_address
    "#{name} #{street_address}, #{city}, #{province.upcase} #{postal_code} Canada"
  end
end

app/models/store_item.rb
class StoreItem < ApplicationRecord
  belongs_to :store
  belongs_to :item

  has_many :reviews, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :reviews, dependent: :nullify

  validates :first_name, presence: true
      validates :last_name, presence: true

      VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
      validates :email, presence: true,
                        uniqueness: {case_sensitive: false},
                        format: VALID_EMAIL_REGEX
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController


  def index
    # @items = Item.all.where(["name ILIKE ?", "%#{params[:search]}%"])
    @search = Search.new
    # @newsearch = Search.new
    if params[:search_id]
      @search = Search.find(params[:search_id])
      @items = @search.items
      # @items = @search.items.paginate(:page)
    else
      @items = Item.all.search(params[:search]).limit(10)
    end

    respond_to do |format|
      format.html { render } # index.html.erb
      format.js { render } # index.js.erb
    end
  end

  def edit
    @item = Item.find params[:id]
  end

  def update
    @item = Item.find params[:id]
    item_params = params.require(:item).permit([:image])
    @item.update item_params
    redirect_to root_path
  end

  def show
    @review = Review.new

    @item = Item.find(params['id'])
    @itemsShelf = Item.find(params['id']).shelves.find_by_store_id(params['store_id'])
    @store = Store.find(params['store_id'])

    # Bellow line is to show reviews related to an item for a specific store
    @reviews = StoreItem.where(store_id: @store.id, item_id: @item.id).first.reviews.order(created_at: :DESC)

    @hash = Gmaps4rails.build_markers(@store) do |store, marker|
      marker.lat store.latitude
      marker.lng store.longitude
      marker.infowindow store.name
    end

  end


  # private
  # def item_params
  #   params.require(:item).permit(:name, :description, :sale_price, :category_id, :image,)
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="navbar navbar-default navbar-fixed-bottom center-block">
    <div class="sticky-container">
      <div class="col-md-12">
        <ul class="social-network social-circle sticky">
          <li><a href="#" class="icoRss" title="Rss"><i class="fa fa-rss"></i></a></li>
          <li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#" class="icoGoogle" title="Google +"><i class="fa fa-google-plus"></i></a></li>
          <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
        </ul>
			</div>
      </div>
    </div>
  </nav>
</footer>


<!-- <div class="sticky-container">
  <ul class="sticky">
    <li><a href="#" class="icoRss" title="Rss"><i class="fa fa-rss"></i></a></li>
    <li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
    <li><a href="#" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a></li>
    <li><a href="#" class="icoGoogle" title="Google +"><i class="fa fa-google-plus"></i></a></li>
    <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
  </ul>
</div> -->

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-default">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" id="hamburger-button" data-toggle="collapse" data-target="#navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Easy Finder</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/items">Home</a></li>
          <li><a href="#">About</a></li>
          <li><a href="#">Contact</a></li>
          <% if user_signed_in? %>
          <!-- <l1 class="welcoming-user"><a href="#">Welcome</a></l1> -->
          <li><a rel="nofollow" data-method="delete" href="/sessions">Sign Out</a></li>
          <% else %>
          <li><a href="/sessions/new">Sign In</a></li>
          <li><a href="/users/new">Sign Up</a></li>
          <% end %>
          <li>
            <% if @search.present? %>
            <a class="btn btn-default btn-outline btn-circle collapsed"  data-toggle="collapse" href="#nav-collapse1" aria-expanded="false" aria-controls="nav-collapse1">Search</a>
          </li>
        </ul>
        <ul class="collapse nav navbar-nav nav-collapse" id="nav-collapse1">
          <form class="simple-search-field" id="simpleSearchForm" action="/items" accept-charset="UTF-8" method="get" data-remote="true">
            <div class="input-group">
              <input type="text" name="search" value="" class="form-control search-field", remote="true" placeholder="Search for an item...">
              <span class="input-group-btn">
                <input type="submit" name="commit" value="Search" remote="true" class="btn btn-outline search-button" data-disable-with="search">
              </span>

              <span class="input-group-btn">
                <button type="button" class="btn btn-outline search-button" data-toggle="modal" data-target="#searchModal" data-whatever="Search">Custom Search</button>
              </span>
            </div>
          </form>
          <!-- <li><a href="#">Web design</a></li>
          <li><a href="#">Development</a></li>
          <li><a href="#">Graphic design</a></li>
          <li><a href="#">Print</a></li>
          <li><a href="#">Motion</a></li>
          <li><a href="#">Mobile apps</a></li> -->
        </ul>
        <% end %>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
  </nav><!-- /.navbar -->
</header>
<%= render './searches/new' %>

<!-- <script>
  document.getElementById('searchForm').addEventListener('submit', function(e){
    const customSearchForm = document.querySelector('#searchModal');
    customSearchForm.classList.remove('fade in');
    // customSearchForm.classList.remove('fade in');
    // customSearchForm.classList.addClass('fade out');
  })
</script> -->

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/_sidebar.html.erb
<!-- Collapsible sidebar menu -->
<ul class="sidebar-menu">

  <!-- Open menu item -->
  <li class="sidebar-menu-item open">
    <a href="#" class="sidebar-menu-button" data-toggle="sidebar-collapse">Dashboard</a>

    <!-- Submenu -->
    <ul class="sidebar-submenu">
      <li class="sidebar-menu-item active">
        <a href="#" class="sidebar-menu-button">Active menu item</a>
      </li>
      <li class="sidebar-menu-item">
        <a href="#" class="sidebar-menu-button">Regular menu item</a>
      </li>
    </ul>
  </li>

  <!-- Menu item -->
  <li class="sidebar-menu-item">
    <a href="#" class="sidebar-menu-button" data-toggle="sidebar-collapse">Reports</a>

    <!-- Submenu -->
    <ul class="sidebar-submenu">
      <li class="sidebar-menu-item">
        <a href="#" class="sidebar-menu-button">Another menu item</a>
      </li>
      <li class="sidebar-menu-item">
        <a href="#" class="sidebar-menu-button">Regular menu item</a>
      </li>
    </ul>
  </li>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EasyFinder</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <!-- google font Open Sans -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans">

    <!-- google font Open Sans -->
    <!-- google font Bree Serif -->
    <link href="https://fonts.googleapis.com/css?family=Bree+Serif|Open+Sans:300,400,600" rel="stylesheet">
    <script src="//maps.google.com/maps/api/js?key=AIzaSyCC9NeRnWOWjGrZQ0lsgGFDFIFi69vG-gA"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <!-- <% if user_signed_in? %>
    Hello <%= current_user.first_name %>

    <%= link_to 'Sign Out', sessions_path, method: :delete  %>
    <% else %>
    |
    <%= link_to 'Sign In', new_session_path %>
    |
    <%= link_to 'Sign Up', new_user_path %>
    <% end %> -->


    <div class="container">
      <div class="row">
        <!-- <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="background:skyblue;"> -->
          <!-- <#%= render 'layouts/navigation.html.erb' %> -->
          <div id="flash_message">
            <% if flash[:notice] %>
            <div class='alert alert-success'><%= flash[:notice] %></div>
            <% elsif flash[:alert] %>
            <div class='alert alert-danger'><%= flash[:alert] %></div>
            <% end %>
          </div>
        <!-- </div> -->
      </div>
    </div>
    <div class="main-container-holder">
      <div class="container main-container">
        <%= yield %>
      </div>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>